apiVersion: v1
kind: ServiceAccount
metadata:
  name: binpack-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binpack-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: binpack-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: binpack-scheduler-config
  namespace: kube-system
data:
  binpack-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
      - schedulerName: binpack-scheduler
        pluginConfig:
        - name: RequestedToCapacityRatio
          args:
            shape:
              - utilization: 0
                score: 0
              - utilization: 100
                score: 100
            resources:
              - name: cpu
                weight: 1
              - name: nvidia.com/gpu
                weight: 10
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binpack-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: binpack-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: binpack-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: binpack-scheduler
      containers:
      - command:
        - kube-scheduler
        - --config=/etc/kubernetes/binpack-scheduler/binpack-scheduler-config.yaml
        image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.21.12
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: kube-second-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts:
          - name: config-volume
            mountPath: /etc/kubernetes/binpack-scheduler
      hostNetwork: false
      hostPID: false
      volumes:
        - name: config-volume
          configMap:
            name: binpack-scheduler-config
